# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ../database:/var/lib/postgresql/data
    env_file: ../.env 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  redis:
    image: redis
    ports:
      - 6379:6379
      