# Generated by Django 4.2.6 on 2023-11-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
