# Generated by Django 4.2.6 on 2023-11-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_bosh_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bosh',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(5, '⭐⭐⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (1, '⭐')], null=True),
        ),
    ]
