# Generated by Django 4.2.6 on 2023-11-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_review_rating_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (2, '⭐⭐'), (5, '⭐⭐⭐⭐⭐'), (1, '⭐')], null=True),
        ),
    ]
