# Generated by Django 4.2.6 on 2023-11-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(4, '⭐⭐⭐⭐'), (2, '⭐⭐'), (5, '⭐⭐⭐⭐⭐'), (1, '⭐'), (3, '⭐⭐⭐')], null=True),
        ),
    ]
