# Generated by Django 4.2.6 on 2023-11-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(4, '⭐⭐⭐⭐'), (3, '⭐⭐⭐'), (1, '⭐'), (5, '⭐⭐⭐⭐⭐'), (2, '⭐⭐')], null=True),
        ),
    ]
