# Generated by Django 4.2.6 on 2023-11-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_variant_rating'),
        ('account', '0024_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐'), (1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐')], null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vvv', to='product.variant'),
        ),
    ]
