# Generated by Django 4.2.6 on 2023-11-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_review_rating_alter_review_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(4, '⭐⭐⭐⭐'), (1, '⭐'), (3, '⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐'), (2, '⭐⭐')], null=True),
        ),
    ]
