# Generated by Django 4.2.6 on 2023-11-20 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(3, '⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐'), (2, '⭐⭐'), (4, '⭐⭐⭐⭐'), (1, '⭐')], null=True),
        ),
    ]
