# Use postgres/example user/password credentials
version: '3.1'

services:

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./static/:/code/static/
      - ./media/:/code/media/
    depends_on:
      - web

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file: .env 
  
  web:
    container_name: multikart
    build: .
    command:  gunicorn --bind 0.0.0.0:8000 multikart.wsgi
    volumes:
        - ./media:/code/media
        - ./static:/code/static
    ports:
      - 8000:8000
    depends_on:
      - "db"
      - "redis"
    # environment:
    #   - DEBUG=False
    env_file: .env

  # celery:
  #   container_name: celery
  #   command: celery -A multikart worker --beat --scheduler django --loglevel=info
  #   build: 
  #     context: .
  #     dockerfile: celery.dockerfile
  #   depends_on: 
  #     - "db"
  #     - "redis"
  #   env_file: .env

  redis:
    image: redis
    ports:
      - 6379:6379
      