# Generated by Django 4.2.3 on 2023-10-20 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='slug_az',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='slug_en',
        ),
        migrations.AlterField(
            model_name='image',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_image', to='product.variant'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_variant', to='product.product'),
        ),
    ]
