# Generated by Django 4.2.6 on 2023-10-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_color_size_remove_propertyvalue_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='general_stock',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='new_status',
        ),
        migrations.AddField(
            model_name='product',
            name='general_stock',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variant',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='title_az',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
