# Generated by Django 4.2.6 on 2023-10-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_image_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='variant',
        ),
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ozu', to='product.image'),
            preserve_default=False,
        ),
    ]
