# Generated by Django 4.2.6 on 2023-10-28 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_variant_image_image_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_status',
        ),
        migrations.AddField(
            model_name='variant',
            name='new_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_images', to='product.variant'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_variants', to='product.product'),
        ),
    ]
