# Generated by Django 4.2.6 on 2023-11-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_desc_alter_product_desc_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_main_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_media/'),
        ),
    ]
