# Generated by Django 4.2.6 on 2023-11-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_variant_is_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='rating',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
