# Generated by Django 4.2.1 on 2023-07-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField()),
                ('flat', models.CharField()),
                ('address', models.TextField()),
                ('zip_code', models.IntegerField()),
                ('country', models.CharField()),
                ('city', models.CharField()),
                ('region', models.CharField()),
                ('shipping', models.BooleanField()),
                ('payment', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
