# Generated by Django 4.2.6 on 2023-11-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_alter_cartitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
